name: Compilación Apple Silicon v2.7.2
on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    # Esta máquina es Apple Silicon nativa
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar Dependencias
        run: pip install pandas numpy requests pyinstaller openpyxl
      - name: Compilar para Apple Silicon
        run: |
          cd asistente_fsr
          python3 -m PyInstaller --clean --onedir --windowed \
            --add-data "logo.png:." \
            --name "Asistente.Fiscal.F910.vSilic.2.7.2" onev2.7.2.py
      - name: Comprimir para descarga
        run: |
          cd asistente_fsr/dist
          zip -r ../../Asistente.F910.Silicon.zip Asistente.Fiscal.F910.vSilic.2.7.2.app
      - name: Subir a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: App-Mac-Silicon
          path: Asistente.F910.Silicon.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar Dependencias
        run: pip install pandas numpy requests pyinstaller openpyxl
      - name: Compilar para Windows
        run: |
          cd asistente_fsr
          python -m PyInstaller --clean --onefile --windowed \
            --add-data "logo.png;." \
            --name "Asistente.Fiscal.F910.v2.7.2" onev2.7.2.py
      - name: Subir a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: App-Windows-Exe
          path: asistente_fsr/dist/Asistente.Fiscal.F910.v2.7.2.exe
